#! /usr/bin/env bash
set -euo pipefail

echo "Waiting 5 seconds..."
sleep 1s
echo "Waiting 4 seconds..."
sleep 1s
echo "Waiting 3 seconds..."
sleep 1s
echo "Waiting 2 seconds..."
sleep 1s
echo "Waiting 1 seconds..."
sleep 1s
echo "Flashing!"

tmp_dir=$(mktemp -d)
trap "rm -rf ${tmp_dir}" EXIT

[[ ! -f out/glove80.uf2.zip ]] && echo "No firmware found" && exit
unzip out/glove80.uf2.zip -d "${tmp_dir}"

device="$(lsblk -f | grep GLV80 | cut -d' ' -f1)"

sudo mount --mkdir "/dev/${device}" /mnt/glove/
sudo mv "${tmp_dir}/glove80.uf2" "/mnt/glove/CURRENT.UF2"
trap "rm -f out/glove80.uf2.zip" EXIT
sudo umount /mnt/glove/
