#! /usr/bin/env bash
set -euo pipefail

[[ ! -f out/glove80.uf2.zip ]] && echo "No firmware found" && exit
unzip out/glove80.uf2.zip -d out/ && rm out/glove80.uf2.zip

echo "Waiting 5 seconds..."
sleep 1s
echo "Waiting 4 seconds..."
sleep 1s
echo "Waiting 3 seconds..."
sleep 1s
echo "Waiting 2 seconds..."
sleep 1s
echo "Waiting 1 seconds..."
sleep 1s
echo "Flashing!"

device="$(lsblk -f | grep GLV80 | cut -d' ' -f1)"

sudo mount --mkdir "/dev/${device}" /mnt/glove/
sudo mv "out/glove80.uf2" "/mnt/glove/CURRENT.UF2"
sudo umount /mnt/glove/
